version: 2

sources:
  - name: bronze_raw
    description: "Esquema de datos crudos en BigQuery. Contiene tablas externas (GCS) y vinculadas (Google Sheets)."
    quoting:
      database: true
      schema: true
      identifier: true

    database: dwhfinancial
    schema: bronze_raw

    tables:
      - name: bankinter_account
        description: "Tabla cruda con los movimientos de la cuenta Bankinter."

      - name: bankinter_card
        description: "Tabla cruda con los movimientos de la tarjeta Bankinter."

      - name: bankinter_shared
        description: "Tabla cruda con los movimientos de la cuenta compartida Bankinter."

      - name: revolut_account
        description: "Tabla cruda con los movimientos de la cuenta Revolut."

      - name: cash
        description: "Tabla externa vinculada directamente a la Google Sheet de Efectivo."