# ---- cloudbuild.yaml CORREGIDO Y FINAL ----

steps:
  # --- PASO 0: Construir la imagen de Docker ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-dbt-image'
    args:
      - 'build'
      - '--tag=$_IMAGE_TAG'
      - '--cache-from=$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/dbt-transform-job:latest'
      - '.'
    timeout: 1200s

  # --- PASO 1 (NUEVO): Subir (push) la imagen a Artifact Registry ---
  # Este paso asegura que la imagen esté disponible para los siguientes pasos.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-dbt-image'
    waitFor: ['build-dbt-image']
    args: ['push', '$_IMAGE_TAG']

  # --- PASO 2: Escanear la imagen en busca de vulnerabilidades ---
  # Ahora espera a que la imagen sea subida y el comando está corregido.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'scan-for-vulnerabilities'
    waitFor: ['push-dbt-image']
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Comando corregido (sin --sort-by y --limit)
        gcloud artifacts docker images scan $_IMAGE_TAG --format=json > scan_results.json

        if grep -q -E "CRITICAL|HIGH" scan_results.json; then
          echo "❌ Vulnerabilidades críticas o altas encontradas. Revisa el reporte:"
          cat scan_results.json
          exit 1
        else
          echo "✅ No se encontraron vulnerabilidades críticas o altas."
        fi

  # --- PASO 3: Desplegar el Job en Cloud Run ---
  # Ahora este paso encontrará la imagen porque ya fue subida en el Paso 1.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-to-cloud-run'
    waitFor: ['scan-for-vulnerabilities']
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - '$_JOB_NAME'
      - '--image=$_IMAGE_TAG'
      - '--region=$_REGION'
      - '--quiet'

# --- IMÁGENES A SUBIR ---
# Todavía es útil para empujar la etiqueta 'latest' para el caché del próximo build.
images:
  - '$_IMAGE_TAG'
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/dbt-transform-job:latest'

# --- OPCIONES ---
options:
  logging: CLOUD_LOGGING_ONLY

# --- CUENTA DE SERVICIO ---
serviceAccount: projects/$PROJECT_ID/serviceAccounts/cloud-run-build-sa@dwhfinancial.iam.gserviceaccount.com