# ---- cloudbuild.yaml Final y Simplificado ----

steps:
  # --- PASO 0: Construir la imagen con AMBOS tags (SHA y latest) ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-dbt-image'
    args:
      - 'build'
      # Crea el tag único con el SHA del commit para trazabilidad
      - '--tag=$_IMAGE_TAG'
      # Crea también el tag 'latest' para que el caché funcione en el próximo build
      - '--tag=$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/dbt-transform-job:latest'
      # Usa la imagen 'latest' del build anterior como caché para acelerar este
      - '--cache-from=$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/dbt-transform-job:latest'
      - '.'
    timeout: 1200s

  # --- PASO 1: Subir la imagen con su tag único a Artifact Registry ---
  # Esto asegura que la imagen esté disponible para el paso de despliegue.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-dbt-image'
    waitFor: ['build-dbt-image']
    args: ['push', '$_IMAGE_TAG']

  # --- PASO 2: Desplegar el Job en Cloud Run ---
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-to-cloud-run'
    waitFor: ['push-dbt-image']
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - '$_JOB_NAME'
      - '--image=$_IMAGE_TAG'
      - '--region=$_REGION'
      - '--quiet'

# --- IMÁGENES A SUBIR ---
# Cloud Build subirá ambos tags al final del proceso.
images:
  - '$_IMAGE_TAG'
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/dbt-transform-job:latest'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/$PROJECT_ID/serviceAccounts/cloud-run-build-sa@dwhfinancial.iam.gserviceaccount.com