# dbt_project.yml

name: 'mi_pipeline_bancario'
version: '1.0.0'
config-version: 2

profile: 'mi_pipeline_bancario'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración por carpeta
models:
  mi_pipeline_bancario:
    01_bronze:
      +materialized: incremental
      +on_schema_change: sync_all_columns
    02_silver:
      +materialized: incremental
      +unique_key: transaccion_id
    03_gold:
      +materialized: table
      +tags: ['gold', 'final']