mi_pipeline_bancario:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth  # o service-account en producción
      project: dwhfinancial
      schema: dbt_tmp
      threads: 4
      retries: 1