mi_pipeline_bancario:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: dwhfinancial
      schema: bronze_standard
      keyfile: /tmp/gcp_key.json
      threads: 4
