name: 'mi_pipeline_bancario'
version: '1.0.0'
config-version: 2

profile: 'mi_pipeline_bancario'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de modelos
models:
  mi_pipeline_bancario:
    # --- ACTIVAR PERSISTENCIA DE DOCUMENTACIÓN (GLOBAL) ---
    +persist_docs:
      relation: true   # Descripción de la tabla
      columns: true    # Descripción de cada columna

    A1_bronze:
      +materialized: incremental
      +unique_key: hash_id
      +on_schema_change: sync_all_columns
      +schema: bronze_standard

    A2_silver:
      +materialized: incremental
      +unique_key: hash_id
      +schema: silver

    A3_gold:
      +materialized: table
      +tags: ['gold', 'final']
      +schema: gold

seeds:
  mi_pipeline_bancario:
    +schema: mappings