# models/sources.yml

version: 2

sources:
  - name: bronze_raw
    quoting:
      database: true
      schema: true
      identifier: true
    
    database: dwhfinancial
    schema: bronze_raw

    tables:
      - name: bankinter_account
        description: "Tabla cruda con los movimientos de la cuenta Bankinter."
      - name: bankinter_card
        description: "Tabla cruda con los movimientos de la tarjeta Bankinter."
      - name: bankinter_shared
        description: "Tabla cruda con los movimientos de la cuenta compartida Bankinter."
      - name: revolut_account
        description: "Tabla cruda con los movimientos de la cuenta Revolut."
        