# models/sources.yml

version: 2

sources:
  - name: bronze_raw
    schema: bronze_raw
    database: dwhfinancial
    tables:
      - name: bankinter_account
        description: "Tabla cruda con los movimientos de la cuenta Bankinter."
      - name: bankinter_card
        description: "Tabla cruda con los movimientos de la tarjeta Bankinter."