name: 'dwhfinancial'
version: '1.0.0'
config-version: 2

profile: 'dwhfinancial_profile'

model-paths: ["models"]
source-paths: ["sources"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dwhfinancial:
    bronze:
      +schema: dwh_02_bronze
      +materialized: incremental
      +full_refresh: false
    silver:
      +schema: dwh_03_silver
      +materialized: incremental
      +full_refresh: false
    gold:
      +schema: dwh_04_gold
      +materialized: table
