version: 2
sources:
  - name: financial_raw
    database: dwhfinancial # Reemplazar con tu ID de proyecto
    schema: dwh_01_raw # Tu dataset raw
    tables:
      - name: bankinter_account
      - name: revolut_account
      # Agrega aquí futuras tablas externas
