# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy Full Financial Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: 'dwhfinancial'
  PROJECT_NUMBER: '675312276583'
  GCS_BUCKET: 'dwhfinancial-data-feed'
  BIGQUERY_DATASET: 'financial_data'
  BIGQUERY_TABLE_RAW: 'data_raw'
  DRIVE_SECRET_NAME: 'drive-service-account-key'
  REGION: 'europe-west1'
  DRIVE_CHECK_TOPIC: 'drive-check-topic'

  FOLDER_ID_PENDING_ACCOUNT: '1P1O9XUaFA7pPmXufRN0xMIfU94zvYxPS'
  FOLDER_ID_PROCESSED_ACCOUNT: '18JQrL2GxmRFHVl8xVa0SYj_nhdpNLT18'
  FOLDER_ID_PENDING_CARD: '1cXsLTPgcSwBB-TQPxXq-eio12MZAPIbm'
  FOLDER_ID_PROCESSED_CARD: '191Xlqc_YUTzOOvlw56pQxfEuBZOzrjnN'

jobs:
  deploy-pipeline:
    name: Deploy Full Pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy ETL-CUENTA-to-GCS Function
      run: |
        gcloud functions deploy etl-cuenta-to-gcs \
          --gen2 \
          --runtime=python311 \
          --region=${{ env.REGION }} \
          --source=./cloud_functions/drive_to_gcs_account_statements \
          --entry-point=main \
          --trigger-topic=${{ env.DRIVE_CHECK_TOPIC }} \
          --set-env-vars="GCP_PROJECT=${{ env.PROJECT_ID }},BUCKET_NAME=${{ env.GCS_BUCKET }},DRIVE_SECRET_NAME=${{ env.DRIVE_SECRET_NAME }},FOLDER_ID_PENDING_ACCOUNT=${{ env.FOLDER_ID_PENDING_ACCOUNT }},FOLDER_ID_PROCESSED_ACCOUNT=${{ env.FOLDER_ID_PROCESSED_ACCOUNT }}"

    - name: Deploy ETL-TARJETA-to-GCS Function
      run: |
        gcloud functions deploy etl-tarjeta-to-gcs \
          --gen2 \
          --runtime=python311 \
          --region=${{ env.REGION }} \
          --source=./cloud_functions/drive_to_gcs_card_payments \
          --entry-point=main \
          --trigger-topic=${{ env.DRIVE_CHECK_TOPIC }} \
          --set-env-vars="GCP_PROJECT=${{ env.PROJECT_ID }},BUCKET_NAME=${{ env.GCS_BUCKET }},DRIVE_SECRET_NAME=${{ env.DRIVE_SECRET_NAME }},FOLDER_ID_PENDING_CARD=${{ env.FOLDER_ID_PENDING_CARD }},FOLDER_ID_PROCESSED_CARD=${{ env.FOLDER_ID_PROCESSED_CARD }}"

    - name: Deploy GCS-to-BigQuery Function
      run: |
        gcloud functions deploy etl-gcs-to-bq \
          --gen2 \
          --runtime=python311 \
          --region=${{ env.REGION }} \
          --source=./cloud_functions/gcs_to_bq \
          --entry-point=main \
          --trigger-event-filters="type=google.cloud.storage.object.v1.finalized,bucket=${{ env.GCS_BUCKET }}" \
          --trigger-location=eu \
          --set-env-vars="GCP_PROJECT=${{ env.PROJECT_ID }},BIGQUERY_DATASET=${{ env.BIGQUERY_DATASET }},BIGQUERY_TABLE_RAW=${{ env.BIGQUERY_TABLE_RAW }}"

    - name: Run BigQuery Transformation Script
      run: |
        echo "Ejecutando script de transformación en BigQuery..."
        bq query --use_legacy_sql=false < queries/A0_raw_to_standard.sql