# Este workflow sincroniza el contenido del repositorio con un bucket de GCS

name: Mirror Source Code to GCS

# Activador: Se ejecuta en cada push a la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  mirror:
    name: Mirror to Google Cloud Storage
    runs-on: ubuntu-latest

    # Permisos necesarios
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # --- Paso 1: Checkout del código ---
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Paso 2: Autenticación con Google Cloud ---
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        # Reemplaza con el nombre completo de tu Workload Identity Pool Provider
        workload_identity_provider: 'projects/675312276583/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-deployer@dwhfinancial.iam.gserviceaccount.com'

    # --- Paso 3: Configurar gcloud/gsutil ---
    # Necesitamos este paso para poder usar el comando gsutil
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # --- Paso 4 (NUEVO): Sincronizar el repositorio con el bucket ---
    # Usamos gsutil rsync para crear un espejo del directorio actual en el bucket
    - name: Sync repository to GCS bucket
      run: |
        echo "Sincronizando el repositorio con el bucket de GCS..."
        gsutil -m rsync -d -r . gs://dwhfinancial-data-repo