# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Upload repository files to GCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: 'dwhfinancial'
  PROJECT_NUMBER: '675312276583'
  # ¡NUEVO! Define el nombre de tu bucket para la copia de seguridad.
  GCS_BUCKET_REPO_BACKUP: 'dwhfinancial-repo-backup' 

jobs:
  backup:
    name: Mirror Repository to GCS
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # 1. Checkout del código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Autenticación con Google Cloud
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    # 3. Configurar el SDK de Google Cloud
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # 4. Sincronizar los archivos con el bucket de GCS
    - name: Sync repository to GCS bucket
      run: |
        echo "Sincronizando el repositorio con gs://${{ env.GCS_BUCKET_REPO_BACKUP }}..."
        gsutil -m rsync -d -r . gs://${{ env.GCS_BUCKET_REPO_BACKUP }}
